version: '3'
services:
  # Nging service. Serves the project folder and uses the 8001 port on the host machine.
  nginx:
    build:
      context: .
      dockerfile: Nginx-Dockerfile
    volumes:
      - './project/:/var/www/project/'
    ports:
      - '8001:80'
    networks:
      - default
    depends_on:
      - mysql
  # PHP service. Contains the symfony installation and the whole project.
  php:
    build:
      context: .
      dockerfile: Php-Dockerfile
    environment:
      APP_ENV: dev
    volumes:
      - './project/:/var/www/project/'
    networks:
      - default
    depends_on:
      - mysql
  # MYSQL Service, uses the mysql image and the 3306 host port. The default auth command is for Symfony's ORM compatibility,
  mysql:
    image: mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--default_authentication-plugin=mysql_native_password'
    environment:
      MYSQL_DATABASE: timetracker
      MYSQL_ROOT_PASSWORD: polestecha
    ports:
      - '3306:3306'
    volumes:
      - './mysql/:/var/lib/mysql'
    networks:
      - default
networks:
  default:
