#index:
#    path: /
#    controller: App\Controller\DefaultController::index

base:
  path: /test
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: 'base.html.twig'